name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: service
    attributes:
      label: Target Service
      description: Which service would this feature be implemented in?
      options:
        - Frontend Service
        - Platform Service
        - Agent Service
        - Documentation
        - Infrastructure/DevOps
        - Multiple Services
        - Other
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New Feature
        - Enhancement
        - Performance Improvement
        - Developer Experience
        - User Experience
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation?
      placeholder: |
        As a [user type], I want to [goal] so that [benefit].

        Currently, [describe the limitation or pain point]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: Describe how this feature would work...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: Describe alternative approaches...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have ideas about how to implement this feature, share them here.
        Include technical details, API changes, UI mockups, etc.
      placeholder: |
        Technical approach:
        - API changes: ...
        - UI changes: ...
        - Database changes: ...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking work)
        - High (important for workflow)
        - Medium (nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: dropdown
    id: release
    attributes:
      label: Target Release
      description: Which release version would you like this in?
      options:
        - v0.1.0
        - v0.2.0
        - v0.3.0
        - v1.0.0
        - Future Release
        - Not Sure

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: |
        What are the conditions that must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Tests added
        - [ ] Documentation updated

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
